//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GUI.TimeTrackerServerReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="TimeTrackerServerReference.IRecords")]
    public interface IRecords {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRecords/GetRecordsData", ReplyAction="http://tempuri.org/IRecords/GetRecordsDataResponse")]
        WCFLibrary.DbRecord[] GetRecordsData();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRecords/GetRecordsData", ReplyAction="http://tempuri.org/IRecords/GetRecordsDataResponse")]
        System.Threading.Tasks.Task<WCFLibrary.DbRecord[]> GetRecordsDataAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IRecordsChannel : GUI.TimeTrackerServerReference.IRecords, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class RecordsClient : System.ServiceModel.ClientBase<GUI.TimeTrackerServerReference.IRecords>, GUI.TimeTrackerServerReference.IRecords {
        
        public RecordsClient() {
        }
        
        public RecordsClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public RecordsClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RecordsClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RecordsClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public WCFLibrary.DbRecord[] GetRecordsData() {
            return base.Channel.GetRecordsData();
        }
        
        public System.Threading.Tasks.Task<WCFLibrary.DbRecord[]> GetRecordsDataAsync() {
            return base.Channel.GetRecordsDataAsync();
        }
    }
}
